# ========================================================================================
#
# Configuration for the media synchronization script (sync_photos.sh)
#
# ========================================================================================

# ----------------------------------------
# SECTION FOR PHOTO SYNCHRONIZATION
# ----------------------------------------
photo_sync:
  enabled: true
  share_name: "Fotos"
  quota_gb: 5 # Storage quota just for photos within the common cache
  max_pics_per_album: 50
  # Regex to filter the top-level directories (e.g., years)
  filter_root_folders: "/[0-9][0-9][0-9][0-9]/"
  # Pipe-separated list of file extensions to sync
  file_extensions: "jpg|jpeg|png|heic"
  # Percentage of the photo quota that should be full before video sync starts
  video_sync_threshold_pct: 90

# ----------------------------------------
# SECTION FOR VIDEO SYNCHRONIZATION
# ----------------------------------------
video_sync:
  enabled: true
  share_name: "video/Video" # Separate share for videos
  quota_gb: 10 # Storage quota just for videos within the common cache
  max_pics_per_album: 2 # Max videos to pull from a selected album
  # Regex to filter the top-level directories (e.g., years)
  filter_root_folders: "/[0-9][0-9][0-9][0-9]/"
  # Pipe-separated list of video file extensions to sync
  # file_extensions: "mp4|mov|avi|mkv"
  file_extensions: "mp4"

# ----------------------------------------
# COMMON SETTINGS (for both photo and video sync)
# ----------------------------------------
common:
  server_ip: "192.168.178.26"
  credentials_file: "~/.smb_credentials"
  domain: ""
  smb_version: "3.0"
  # The single, unified cache directory for all media
  cache_path: "~/picframe/cache"
  # Temporary mount point for the remote shares
  mount_point: "/mnt/server_share"
  # Log file to track shown albums to avoid immediate repeats
  shown_albums_log: "~/picframe/shown_albums.log"
  # Randomly pick folders from root (e.g., years)
  shuffle_folder_root: true
  # Randomly pick subfolders (e.g., locations)
  shuffle_album_subfolder: true